apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-se-assistant
  namespace: llm-se-assistant
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: llm-se-assistant.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llm-se-assistant
                port:
                  number: 80
